#!/usr/bin/env python3
"""Repo Steward dashboard server.

Static file serving plus a minimal control API:
  GET  /api/status            -> {"tick_active": bool, "mode": "draft"|"live"}
  POST /api/tick              -> start one steward tick (refused while one runs)
  POST /api/approve           -> execute a staged action set via gh
        body: {"repo": "llmfit", "items": ["pr-646", ...]}

Approvals run under the local gh auth — i.e. as Alex, because a human clicked.
Ledger writes are refused while a tick is active to avoid racing the steward.
"""
import json
import os
import re
import subprocess
import time
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path

ROOT = Path(__file__).resolve().parent
PORT = int(os.environ.get("STEWARD_PORT", "8377"))
HOST = os.environ.get("STEWARD_HOST", "0.0.0.0")

PLACEHOLDER = """<meta charset="utf-8"><title>Repo Steward</title>
<body style="font-family:system-ui;max-width:600px;margin:80px auto;line-height:1.6">
<h1>🤝 Repo Steward</h1>
<p>No dashboard yet — it's generated by the first tick. Start one with:</p>
<pre>systemctl --user start repo-steward.service</pre>
<p>then refresh. Ticks take a few minutes on a large backlog.</p></body>"""


def repo_map():
    """Short repo name -> owner/repo, parsed from config.yaml."""
    m = {}
    for line in (ROOT / "config.yaml").read_text().splitlines():
        match = re.match(r"\s*-\s*name:\s*(\S+/\S+)", line)
        if match:
            full = match.group(1)
            m[full.split("/")[1]] = full
    return m


def steward_mode():
    match = re.search(r"^mode:\s*(\w+)", (ROOT / "config.yaml").read_text(), re.M)
    return match.group(1) if match else "draft"


def tick_active():
    state = subprocess.run(
        ["systemctl", "--user", "is-active", "repo-steward.service"],
        capture_output=True, text=True,
    ).stdout.strip()
    return state in ("active", "activating")


def run_gh(args):
    p = subprocess.run(["gh"] + args, capture_output=True, text=True, timeout=60)
    return p.returncode == 0, (p.stdout + p.stderr).strip()


def execute_action(full_repo, number, item_type, action):
    """Execute one staged action. Returns (ok, detail)."""
    kind = action.get("kind", "")
    body = action.get("body", "")
    labels = action.get("labels", [])
    results = []

    if item_type == "pr" and "review" in kind:
        flag = "--approve" if "approve" in kind else (
            "--request-changes" if "request" in kind else "--comment")
        ok, out = run_gh(["pr", "review", str(number), "-R", full_repo, flag, "--body", body])
        results.append((ok, f"pr review {flag}: {out[:200]}"))
    elif body:
        sub = "pr" if item_type == "pr" else "issue"
        ok, out = run_gh([sub, "comment", str(number), "-R", full_repo, "--body", body])
        results.append((ok, f"{sub} comment: {out[:200]}"))

    if labels and item_type == "issue":
        ok, out = run_gh(["issue", "edit", str(number), "-R", full_repo,
                          "--add-label", ",".join(labels)])
        results.append((ok, f"labels: {out[:200]}"))

    return all(ok for ok, _ in results), "; ".join(d for _, d in results)


class Handler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    def _json(self, code, obj):
        payload = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def do_GET(self):
        if self.path == "/api/status":
            return self._json(200, {"tick_active": tick_active(), "mode": steward_mode()})
        if self.path == "/api/metrics":
            def read_jsonl(name):
                p = ROOT / name
                if not p.exists():
                    return []
                out = []
                for line in p.read_text().splitlines():
                    try:
                        out.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
                return out
            return self._json(200, {"metrics": read_jsonl("metrics.jsonl"),
                                    "usage": read_jsonl("usage.jsonl")})
        if self.path == "/api/uptime":
            state_path = ROOT / "uptime_state.json"
            state = json.loads(state_path.read_text()) if state_path.exists() else {}
            samples = []
            p = ROOT / "uptime.jsonl"
            if p.exists():
                lines = p.read_text().splitlines()[-2400:]  # ~2 days at 4 sites/5min
                for line in lines:
                    try:
                        samples.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
            return self._json(200, {"state": state, "samples": samples})
        if self.path == "/":
            self.send_response(302)
            self.send_header("Location", "/dashboard.html")
            self.end_headers()
            return
        if self.path.startswith("/dashboard.html") and not (ROOT / "dashboard.html").exists():
            payload = PLACEHOLDER.encode()
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            self.wfile.write(payload)
            return
        return super().do_GET()

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        try:
            req = json.loads(self.rfile.read(length) or b"{}")
        except json.JSONDecodeError:
            return self._json(400, {"error": "bad json"})

        if self.path == "/api/tick":
            if tick_active():
                return self._json(409, {"error": "a tick is already running"})
            subprocess.run(["systemctl", "--user", "start", "--no-block",
                            "repo-steward.service"], check=False)
            return self._json(200, {"started": True})

        if self.path == "/api/mode":
            new_mode = req.get("mode")
            if new_mode not in ("draft", "live"):
                return self._json(400, {"error": "mode must be 'draft' or 'live'"})
            cfg_path = ROOT / "config.yaml"
            cfg = cfg_path.read_text()
            cfg, n = re.subn(r"^mode:\s*\w+", f"mode: {new_mode}", cfg, count=1, flags=re.M)
            if not n:
                return self._json(500, {"error": "no 'mode:' line found in config.yaml"})
            cfg_path.write_text(cfg)
            return self._json(200, {"mode": new_mode})

        if self.path == "/api/approve":
            if tick_active():
                return self._json(409, {"error": "tick running — try again when it finishes"})
            repos = repo_map()
            short = req.get("repo", "")
            full = repos.get(short)
            if not full:
                return self._json(400, {"error": f"unknown repo {short!r}"})
            ledger_path = ROOT / "state" / f"{short}.json"
            ledger = json.loads(ledger_path.read_text())
            outcomes = {}
            for key in req.get("items", []):
                item = ledger["items"].get(key)
                if not item:
                    outcomes[key] = {"ok": False, "detail": "not in ledger"}
                    continue
                number = key.split("-", 1)[1]
                item_ok, details = True, []
                for action in item.get("staged_actions", []):
                    if action.get("executed_at"):
                        continue
                    ok, detail = execute_action(full, number, item["type"], action)
                    details.append(detail)
                    if ok:
                        action["executed_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
                    item_ok = item_ok and ok
                if item_ok:
                    item["status"] = "posted"
                    item["last_action"] = "approved by maintainer via dashboard; posted"
                    item["last_action_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
                outcomes[key] = {"ok": item_ok, "detail": "; ".join(details)}
            ledger_path.write_text(json.dumps(ledger, indent=2))
            with open(ROOT / "approvals.jsonl", "a") as f:
                f.write(json.dumps({"ts": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                                    "repo": short, "outcomes": outcomes}) + "\n")
            return self._json(200, {"outcomes": outcomes})

        return self._json(404, {"error": "unknown endpoint"})

    def log_message(self, fmt, *args):
        pass  # keep journal quiet; approvals are logged to approvals.jsonl


if __name__ == "__main__":
    ThreadingHTTPServer((HOST, PORT), Handler).serve_forever()
