#!/usr/bin/env python3
"""Repo Steward dashboard server.

Static file serving plus a minimal control API:
  GET  /api/status            -> {tick_active, mode, elapsed_sec, eta_sec, schedule}
  GET  /api/progress          -> {steps: [...]}  (per-item progress the tick emits)
  GET  /api/metrics|uptime    -> chart data
  POST /api/tick              -> start one steward tick (refused while one runs)
  POST /api/mode              -> {"mode": "draft"|"live"}  (rewrites config.yaml)
  POST /api/schedule          -> {"preset": "manual"|"hourly"|"6h"|"daily"|"weekly"}
  POST /api/limits            -> {"substantive": N, "light": N}  (per-tick work caps)
  GET  /api/staged?repo=&item= -> the ledger item (staged review text, verdict)
  POST /api/approve           -> execute a staged action set via gh
        body: {"repo": "llmfit", "items": ["pr-646", ...]}
  POST /api/dismiss           -> mark items dismissed (drops off the queue, posts nothing)
        body: {"repo": "llmfit", "items": ["pr-646", ...]}

Approvals run under the local gh auth — i.e. as Alex, because a human clicked.
Ledger writes are refused while a tick is active to avoid racing the steward.
"""
import json
import os
import re
import subprocess
import time
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from urllib.parse import urlparse, parse_qs

ROOT = Path(__file__).resolve().parent
PORT = int(os.environ.get("STEWARD_PORT", "8377"))
HOST = os.environ.get("STEWARD_HOST", "0.0.0.0")
UNIT_DIR = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "systemd" / "user"

# OnCalendar presets offered by the dashboard schedule control.
SCHEDULES = {
    "manual": (None, "Manual only"),
    "hourly": ("*-*-* *:17:00", "Hourly"),
    "6h": ("*-*-* 00,06,12,18:17:00", "Every 6 hours"),
    "daily": ("*-*-* 07:00:00", "Daily at 07:00"),
    "weekly": ("Mon *-*-* 07:00:00", "Weekly (Mon 07:00)"),
}

PLACEHOLDER = """<meta charset="utf-8"><title>Repo Steward</title>
<body style="font-family:system-ui;max-width:600px;margin:80px auto;line-height:1.6">
<h1>🤝 Repo Steward</h1>
<p>No dashboard yet — it's generated by the first tick. Start one with:</p>
<pre>systemctl --user start repo-steward.service</pre>
<p>then refresh. Ticks take a few minutes on a large backlog.</p></body>"""


def repo_map():
    """Short repo name -> owner/repo, parsed from config.yaml."""
    m = {}
    for line in (ROOT / "config.yaml").read_text().splitlines():
        match = re.match(r"\s*-\s*name:\s*(\S+/\S+)", line)
        if match:
            full = match.group(1)
            m[full.split("/")[1]] = full
    return m


def steward_mode():
    match = re.search(r"^mode:\s*(\w+)", (ROOT / "config.yaml").read_text(), re.M)
    return match.group(1) if match else "draft"


def steward_signature():
    m = re.search(r'^signature:\s*"(.*)"\s*$', (ROOT / "config.yaml").read_text(), re.M)
    if not m:
        return ""
    # YAML double-quoted: turn the \n escapes into real newlines.
    return m.group(1).replace("\\n", "\n")


def with_signature(body):
    """Ensure the posted body ends with the CURRENT config signature, so a
    change to the signature (or the project URL) takes effect immediately for
    every pending item, regardless of when it was staged."""
    sig = steward_signature()
    if not sig or not body or sig in body:
        return body
    marker = body.find("🤝")           # strip any older baked-in signature
    if marker != -1:
        body = body[:marker].rstrip()
    return body + "\n\n" + sig


def read_limits():
    txt = (ROOT / "config.yaml").read_text()

    def g(key, default):
        m = re.search(r"^\s*" + key + r":\s*(\d+)", txt, re.M)
        return int(m.group(1)) if m else default
    return {"substantive": g("substantive_items_per_tick", 8),
            "light": g("light_items_per_tick", 24)}


def set_limits(sub, light):
    try:
        sub, light = int(sub), int(light)
    except (TypeError, ValueError):
        return False, "limits must be integers"
    if not (1 <= sub <= 100 and 1 <= light <= 200):
        return False, "out of range (substantive 1-100, light 1-200)"
    txt = (ROOT / "config.yaml").read_text()
    txt, n1 = re.subn(r"^(\s*substantive_items_per_tick:\s*)\d+",
                      lambda m: m.group(1) + str(sub), txt, count=1, flags=re.M)
    txt, n2 = re.subn(r"^(\s*light_items_per_tick:\s*)\d+",
                      lambda m: m.group(1) + str(light), txt, count=1, flags=re.M)
    if not (n1 and n2):
        return False, "limits block not found in config.yaml"
    (ROOT / "config.yaml").write_text(txt)
    return True, {"substantive": sub, "light": light}


def tick_active():
    state = subprocess.run(
        ["systemctl", "--user", "is-active", "repo-steward.service"],
        capture_output=True, text=True,
    ).stdout.strip()
    return state in ("active", "activating")


def tick_elapsed_sec():
    """Seconds the running tick has been alive, or None if not running."""
    pid = subprocess.run(
        ["systemctl", "--user", "show", "repo-steward.service", "-p", "MainPID", "--value"],
        capture_output=True, text=True).stdout.strip()
    if not pid or pid == "0":
        return None
    et = subprocess.run(["ps", "-o", "etimes=", "-p", pid],
                        capture_output=True, text=True).stdout.strip()
    return int(et) if et.isdigit() else None


def eta_sec():
    """Median duration of recent measured ticks. Returns None until there are
    at least 3 samples — below that a single number is noise, not an estimate."""
    p = ROOT / "usage.jsonl"
    if not p.exists():
        return None
    durs = []
    for line in p.read_text().splitlines():
        try:
            d = json.loads(line).get("duration_ms")
            if d:
                durs.append(d / 1000)
        except json.JSONDecodeError:
            pass
    if len(durs) < 3:
        return None
    durs.sort()
    return int(durs[len(durs) // 2])


def tick_progress():
    """Deterministic tick position: how many of the configured repos have
    actually been touched (ledger rewritten this tick, or seen in the progress
    feed), plus the latest free-text activity note. Does not trust the LLM's
    self-assigned repo indices."""
    el = tick_elapsed_sec()
    if el is None:
        return None
    start = time.time() - el - 5
    seen = set()
    for p in (ROOT / "state").glob("*.json"):
        try:
            if p.stat().st_mtime >= start:
                seen.add(p.stem)
        except OSError:
            pass
    note = None
    prog = ROOT / "progress.jsonl"
    if prog.exists():
        for line in prog.read_text().splitlines():
            try:
                o = json.loads(line)
            except json.JSONDecodeError:
                continue
            r = o.get("repo")
            if r and r != "fleet":
                seen.add(r)
            if o.get("phase") in ("repo", "item") and o.get("msg"):
                note = (r + ": " if r else "") + o["msg"]
    total = len(repo_map()) or 1
    return {"repos_done": min(len(seen), total), "repos_total": total, "note": note}


def current_schedule():
    active = subprocess.run(
        ["systemctl", "--user", "is-active", "repo-steward.timer"],
        capture_output=True, text=True).stdout.strip() == "active"
    oncal, preset = None, "manual"
    tf = UNIT_DIR / "repo-steward.timer"
    if tf.exists():
        m = re.search(r"^OnCalendar=(.+)$", tf.read_text(), re.M)
        if m:
            oncal = m.group(1).strip()
    if active and oncal:
        preset = next((k for k, (cal, _) in SCHEDULES.items() if cal == oncal), "custom")
    label = SCHEDULES.get(preset, (None, oncal or "custom"))[1] if preset != "custom" else (oncal or "custom")
    return {"enabled": active, "oncalendar": oncal, "preset": preset if active else "manual",
            "label": label if active else "Manual only"}


def set_schedule(preset):
    if preset not in SCHEDULES:
        return False, f"unknown preset {preset!r}"
    tf = UNIT_DIR / "repo-steward.timer"
    if preset == "manual":
        subprocess.run(["systemctl", "--user", "disable", "--now", "repo-steward.timer"],
                       capture_output=True, text=True)
        return True, "manual"
    if not tf.exists():
        return False, "timer unit not found — run install.sh first"
    oncal = SCHEDULES[preset][0]
    text = tf.read_text()
    # Replace all OnCalendar lines with a single one for the chosen preset.
    lines = [ln for ln in text.splitlines() if not ln.startswith("OnCalendar=")]
    out = []
    for ln in lines:
        out.append(ln)
        if ln.strip() == "[Timer]":
            out.append(f"OnCalendar={oncal}")
    tf.write_text("\n".join(out) + "\n")
    subprocess.run(["systemctl", "--user", "daemon-reload"], capture_output=True)
    r = subprocess.run(["systemctl", "--user", "enable", "--now", "repo-steward.timer"],
                       capture_output=True, text=True)
    return r.returncode == 0, (r.stderr.strip() or preset)


def run_gh(args):
    p = subprocess.run(["gh"] + args, capture_output=True, text=True, timeout=60)
    return p.returncode == 0, (p.stdout + p.stderr).strip()


def execute_action(full_repo, number, item_type, action):
    """Execute one staged action. Returns (ok, detail)."""
    kind = action.get("kind", "")
    body = with_signature(action.get("body", ""))
    labels = action.get("labels", [])
    results = []

    if item_type == "pr" and "review" in kind:
        flag = "--approve" if "approve" in kind else (
            "--request-changes" if "request" in kind else "--comment")
        ok, out = run_gh(["pr", "review", str(number), "-R", full_repo, flag, "--body", body])
        results.append((ok, f"pr review {flag}: {out[:200]}"))
    elif body:
        sub = "pr" if item_type == "pr" else "issue"
        ok, out = run_gh([sub, "comment", str(number), "-R", full_repo, "--body", body])
        results.append((ok, f"{sub} comment: {out[:200]}"))

    if labels and item_type == "issue":
        ok, out = run_gh(["issue", "edit", str(number), "-R", full_repo,
                          "--add-label", ",".join(labels)])
        results.append((ok, f"labels: {out[:200]}"))

    return all(ok for ok, _ in results), "; ".join(d for _, d in results)


class Handler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    def _json(self, code, obj):
        payload = json.dumps(obj).encode()
        self.send_response(code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        self.end_headers()
        self.wfile.write(payload)

    def do_GET(self):
        if self.path == "/api/status":
            active = tick_active()
            return self._json(200, {
                "tick_active": active,
                "mode": steward_mode(),
                "elapsed_sec": tick_elapsed_sec() if active else None,
                "eta_sec": eta_sec(),
                "progress": tick_progress() if active else None,
                "schedule": current_schedule(),
                "limits": read_limits(),
            })
        if self.path == "/api/progress":
            steps = []
            p = ROOT / "progress.jsonl"
            if p.exists():
                for line in p.read_text().splitlines()[-60:]:
                    try:
                        steps.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
            return self._json(200, {"steps": steps})
        parsed = urlparse(self.path)
        if parsed.path == "/api/staged":
            qs = parse_qs(parsed.query)
            short = qs.get("repo", [""])[0]
            key = qs.get("item", [""])[0]
            ledger_path = ROOT / "state" / f"{short}.json"
            if not ledger_path.exists():
                return self._json(404, {"error": "no ledger for repo"})
            item = json.loads(ledger_path.read_text())["items"].get(key)
            if not item:
                return self._json(404, {"error": "item not in ledger"})
            return self._json(200, {"item": item})
        if parsed.path == "/api/ghstate":
            qs = parse_qs(parsed.query)
            repo = qs.get("repo", [""])[0]
            num = qs.get("num", [""])[0]
            kind = qs.get("kind", ["issue"])[0]
            if "/" not in repo or not num.isdigit():
                return self._json(400, {"error": "repo=owner/name & numeric num required"})
            ep = "pulls" if kind == "pr" else "issues"
            ok, out = run_gh(["api", f"repos/{repo}/{ep}/{num}",
                              "--jq", "{state:.state, merged:(.merged // false)}"])
            if not ok:
                return self._json(200, {"state": "unknown", "merged": False})
            try:
                return self._json(200, json.loads(out))
            except json.JSONDecodeError:
                return self._json(200, {"state": "unknown", "merged": False})
        if self.path == "/api/metrics":
            def read_jsonl(name):
                p = ROOT / name
                if not p.exists():
                    return []
                out = []
                for line in p.read_text().splitlines():
                    try:
                        out.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
                return out
            return self._json(200, {"metrics": read_jsonl("metrics.jsonl"),
                                    "usage": read_jsonl("usage.jsonl")})
        if self.path == "/api/uptime":
            state_path = ROOT / "uptime_state.json"
            state = json.loads(state_path.read_text()) if state_path.exists() else {}
            samples = []
            p = ROOT / "uptime.jsonl"
            if p.exists():
                lines = p.read_text().splitlines()[-2400:]  # ~2 days at 4 sites/5min
                for line in lines:
                    try:
                        samples.append(json.loads(line))
                    except json.JSONDecodeError:
                        pass
            return self._json(200, {"state": state, "samples": samples})
        if self.path == "/":
            self.send_response(302)
            self.send_header("Location", "/dashboard.html")
            self.end_headers()
            return
        if self.path.startswith("/dashboard.html") and not (ROOT / "dashboard.html").exists():
            payload = PLACEHOLDER.encode()
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(payload)))
            self.end_headers()
            self.wfile.write(payload)
            return
        return super().do_GET()

    def do_POST(self):
        length = int(self.headers.get("Content-Length", 0))
        try:
            req = json.loads(self.rfile.read(length) or b"{}")
        except json.JSONDecodeError:
            return self._json(400, {"error": "bad json"})

        if self.path == "/api/tick":
            if tick_active():
                return self._json(409, {"error": "a tick is already running"})
            subprocess.run(["systemctl", "--user", "start", "--no-block",
                            "repo-steward.service"], check=False)
            return self._json(200, {"started": True})

        if self.path == "/api/mode":
            new_mode = req.get("mode")
            if new_mode not in ("draft", "live"):
                return self._json(400, {"error": "mode must be 'draft' or 'live'"})
            cfg_path = ROOT / "config.yaml"
            cfg = cfg_path.read_text()
            cfg, n = re.subn(r"^mode:\s*\w+", f"mode: {new_mode}", cfg, count=1, flags=re.M)
            if not n:
                return self._json(500, {"error": "no 'mode:' line found in config.yaml"})
            cfg_path.write_text(cfg)
            return self._json(200, {"mode": new_mode})

        if self.path == "/api/schedule":
            ok, detail = set_schedule(req.get("preset", ""))
            if not ok:
                return self._json(400, {"error": detail})
            return self._json(200, {"schedule": current_schedule()})

        if self.path == "/api/limits":
            ok, detail = set_limits(req.get("substantive"), req.get("light"))
            if not ok:
                return self._json(400, {"error": detail})
            return self._json(200, {"limits": detail})

        if self.path == "/api/dismiss":
            if tick_active():
                return self._json(409, {"error": "tick running — try again when it finishes"})
            short = req.get("repo", "")
            ledger_path = ROOT / "state" / f"{short}.json"
            if not ledger_path.exists():
                return self._json(400, {"error": f"unknown repo {short!r}"})
            ledger = json.loads(ledger_path.read_text())
            now = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
            outcomes = {}
            for key in req.get("items", []):
                item = ledger["items"].get(key)
                if not item:
                    outcomes[key] = {"ok": False}
                    continue
                item["status"] = "dismissed"
                item["last_action"] = "dismissed by maintainer via dashboard (not posted)"
                item["last_action_at"] = now
                outcomes[key] = {"ok": True}
            ledger_path.write_text(json.dumps(ledger, indent=2))
            with open(ROOT / "approvals.jsonl", "a") as f:
                f.write(json.dumps({"ts": now, "repo": short, "action": "dismiss",
                                    "outcomes": outcomes}) + "\n")
            return self._json(200, {"outcomes": outcomes})

        if self.path == "/api/approve":
            if tick_active():
                return self._json(409, {"error": "tick running — try again when it finishes"})
            repos = repo_map()
            short = req.get("repo", "")
            full = repos.get(short)
            if not full:
                return self._json(400, {"error": f"unknown repo {short!r}"})
            ledger_path = ROOT / "state" / f"{short}.json"
            ledger = json.loads(ledger_path.read_text())
            outcomes = {}
            for key in req.get("items", []):
                item = ledger["items"].get(key)
                if not item:
                    outcomes[key] = {"ok": False, "detail": "not in ledger"}
                    continue
                number = key.split("-", 1)[1]
                item_ok, details = True, []
                for action in item.get("staged_actions", []):
                    if action.get("executed_at"):
                        continue
                    ok, detail = execute_action(full, number, item["type"], action)
                    details.append(detail)
                    if ok:
                        action["executed_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
                    item_ok = item_ok and ok
                if item_ok:
                    item["status"] = "posted"
                    item["last_action"] = "approved by maintainer via dashboard; posted"
                    item["last_action_at"] = time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime())
                outcomes[key] = {"ok": item_ok, "detail": "; ".join(details)}
            ledger_path.write_text(json.dumps(ledger, indent=2))
            with open(ROOT / "approvals.jsonl", "a") as f:
                f.write(json.dumps({"ts": time.strftime("%Y-%m-%dT%H:%M:%SZ", time.gmtime()),
                                    "repo": short, "outcomes": outcomes}) + "\n")
            return self._json(200, {"outcomes": outcomes})

        return self._json(404, {"error": "unknown endpoint"})

    def log_message(self, fmt, *args):
        pass  # keep journal quiet; approvals are logged to approvals.jsonl


if __name__ == "__main__":
    ThreadingHTTPServer((HOST, PORT), Handler).serve_forever()
